apiVersion: apps/v1
kind: Deployment
metadata:
  name: FilmFlix-app
  labels:
    app: FilmFlix-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: FilmFlix-app
  template:
    metadata:
      labels:
        app: FilmFlix-app
    spec:
      containers:
      - name: FilmFlix-app
        image: amit/FilmFlix:latest
        ports:
        - containerPort: 80
